# Generated by Django 3.1.6 on 2021-02-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210221_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='has_scent',
            field=models.ManyToManyField(blank=True, null=True, to='product.scents'),
        ),
    ]
