# Generated by Django 3.1.6 on 2021-02-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
